[package]
name = "mpl-simplify"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
mpl-ir = { path = "../ir" }
mpl-rewrite = { path = "../rewrite" }
mpl-symbol = { path = "../symbol" }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"

[[test]]
name = "cli"
path = "../../tests/cli.rs"
