[package]
name = "mpl-rewrite"
version = "0.1.9"
edition = "2021"

[dependencies]
egg = "0.9"
mpl-ir = { path = "../ir" }
thiserror = "1"
num-rational = { version = "0.4", features = ["serde"] }
num-traits = "0.2"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "rewrite_simplify"
harness = false
path = "../../benches/rewrite_simplify.rs"

